"""empty message

Revision ID: 29b1c0bb32d0
Revises: 
Create Date: 2017-10-20 15:08:20.849213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b1c0bb32d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hft_treatment_id', sa.Integer(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric')
    # ### end Alembic commands ###
