"""empty message

Revision ID: 976077e8419f
Revises: 29b1c0bb32d0
Create Date: 2017-10-31 16:03:15.057692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976077e8419f'
down_revision = '29b1c0bb32d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric', 'threshold')
    # ### end Alembic commands ###
